#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, formatting and building your project before committing'

# Check Prettier standards
yarn check-format ||
(
  echo '🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮
    Prettier Check Failed. Run yarn format, add changes and try commit again.';
  false;
)

# Check ESLint Standards
yarn lint ||
(
  echo '😤🏀👋😤 Get that weak code out of here! 😤🏀👋😤 
    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false; 
)

# Check TypeScript standards
yarn check-types ||
(
  echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
    Are you seriously trying to write that? Make the changes required above.'
  false;
)

echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# Check build
yarn build ||
(
  echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
    Next build failed: View the errors above to see why.'
  false;
)

# If everything passes... we can proceed to commit
echo '✅✅✅✅ Code looking fresh... I am committing this now. ✅✅✅✅'